spring:
  profiles: test
companyName: RetailShop
companyLogo: RSTest
spring.datasource.username: root
spring.datasource.password: root

---
 
spring:
  profiles: prod
companyName: RetailShop
companyLogo: RSProd
spring.datasource.username: awsmysqldbUserid
spring.datasource.password: awsmysqldbPass